name: Build releases
on:
  workflow_dispatch:
  push:
    tags: ["*"]
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node-version: [22.x]
        arch: [x64]
        include:
          - os: windows-latest
            arch: ia32
          - os: ubuntu-latest
            arch: arm64
          - os: macos-latest
            arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - name: Install dependencies
      run: cd app && npm install --arch=${{ matrix.arch }}
    - name: Make release
      run: cd app && npm run make:${{ matrix.arch == 'ia32' && '32' || (matrix.arch == 'arm64' && 'arm64' || '64') }}
    - name: Upload release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.TOKEN }}
        file: app/out/make/**/*.{exe,zip}
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true